### ISSUE TITLE
aria2一直在连接中。。。

### ISSUE THREAD

**Issue by tinterking** [Xmader/aria-ng-gui#2]

**Comment by tinterking** [comment]
连接不上  是什么原因  求教？？

**Comment by Xmader** [comment]
请问您使用的操作系统是什么？

**Comment by tinterking** [comment]
ubuntu16.04 我刚才搜了一下已经解决了 是因为我的RPC Server模式没有启动
aria2c --enable-rpc --rpc-listen-all --rpc-allow-origin-all -c  --dir /root/downloads -D (-D daemon模式,用于后台执行)
