### ISSUE TITLE
大佬请问64位系统的aria2c为啥还是win32的啊

### ISSUE THREAD

**Issue by RudeTheJack** [Xmader/aria-ng-gui#28]
RT

**Comment by Xmader** [comment]
您好，
`win32` 指的是[操作系统平台名称](https://nodejs.org/api/process.html#process_process_platform)，而不是指 32位的 Windows 系统

**Comment by Xmader** [comment]
从 `v2.1.0` 开始，已经增加打包了 64位 Windows 和 Linux armv7l (可用于树莓派) 的 `aria2c`
