### ISSUE TITLE
程序打开出现问题

### ISSUE THREAD

**Issue by TomLiu2016** [Xmader/aria-ng-gui#30]
![image](https://user-images.githubusercontent.com/20353163/70379822-a4da9a80-18f7-11ea-8d68-cf9acc14b5b2.png)

电脑小白，是不是我没有正确的安装？

**Comment by Xmader** [comment]
由于 MacOS 上的 App Translocation 机制，在 ~/Downloads 文件夹中打开的 APP 会被自动挂载到一个只读文件系统，需要将它移动到其它的文件夹中（通常是 /Applications 中）才能正常打开

参考：https://lapcatsoftware.com/articles/app-translocation.html

https://github.com/Xmader/aria-ng-gui/issues/14#issuecomment-468138320

**Comment by TomLiu2016** [comment]
谢谢！拖到/Application里突然就发现能用了，回来正准备删问题发现已经回复了，太快了吧

**Comment by Xmader** [comment]
之前也有相似的问题，只是把之前的回复复制一遍
