### ISSUE TITLE
希望阻止系统休眠

### ISSUE THREAD

**Issue by zerofancy** [Xmader/aria-ng-gui#34]
作为一个下载工具，阻止系统休眠应该是很重要的功能，毕竟有些文件较大不能立即下完可能希望离开去做别的事情。目前版本似乎没有阻止系统休眠？我现在都是另外打开一个音乐播放器放音乐阻止它休眠……

**Comment by Xmader** [comment]
您好，最新的 ` v3.1.0` 已经添加阻止系统休眠的功能
